# ATIVIDADE1

# for numero in range(2,21,2):
#   print(numero)

# ATVIDADE2

# multiplos_de_5 = range(5,51,5)
# soma = sum(multiplos_de_5)
# print("A soma dos multiplos de 5 até 50 é:",soma)

# ATIVIDADE3

# MULT = 1.5*6.8
# print(MULT)

# ATIVIDADE4

# nome = print)'digite o seu nome')
# comprimento=('olá qual o seu nome')
# print = (comprimento,nome)



# variáveis
#tipos

# numero = 10
# texto = 'olá'
# boleao = True
# real = 6,5

# #calculo
# + - * / ** //

# # função output ()

# print('olá mundo')

# função input()

# nome1, nome2, nome3 = input('digiteo nome') ...
#  -10-9-8-7-6-5-4-3-2-1
#lista = [1,2,3,4,5,6,7,8,9,10]
#     0,1,2,3,4,5,6,7,8,9
# numero5 = lista[4]
# print(list[-5])
# soma = sum(lista)
# comprimento = len(lista)
# maior = msx(lista)
# menor = min(lista)
# print ('soma', soma '/n comprimento', comprimento, 'n/menor' , menor)
# print(f'''soma:',{soma}  
# comprimento {comprimento} 
# menor {menor}''')
# a2 = [1,2,3,4,5,6,7,8,9,10,15,150]

# lista = list(range(1,21,5))
# # ( star stop step by step)
# print(lista)

# # for n in range(1,10)

# n1,n2,n3 = lista
# print(n1,n2,n3)


# ATIVIDADE

conta=(4*6/2)
print(conta)

Soma=(5+7)
print(Soma)

conta=(4*6/2)
print(conta)
conta=(3**4)
print(conta)

soma=(8+12+15/)
print(soma)

soma=(10-2)
soma=(soma*5)
print(soma)

conta=(27/3+5)
print(conta)

print(17%4)

quadrado=(9*3)
print(quadrado*quadrado)

raiz= 81
r= raiz**(1/12)
print(r)

conta=(3*4+20)
print(conta)

conta=(15*2-7)
print(conta)

print(5**3)

soma=(17+21+25)
print(soma//3)

conta=(11*2+7)
print(conta)

soma=(15-3*8/2)
print(soma)

print(2**10)


